version: "3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - 8080:80
    volumes:
      - /portainer/appdata/FileBrowser:/data
      - /portainer/appdata:/srv
    restart: always
