---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- JELLYFIN_PublishedServerUrl=https://jellyfin.yourdomain.org/ #optional
    volumes:
      - /container-data/jellyfin/config:/config
      #- nas:/data:ro
      #- /mnt/debridlink:/data
      - /mnt/debridlink:/mnt/debridlink:ro
      - /srv/jellyfin:/data
    networks:
      nginx:
        ipv4_address: 172.20.0.7
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
networks:
    nginx:
      external: true
      name: nginx
volumes:
  nas:
    external: true