version: "3"
services:
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      nginx:
        ipv4_address: 172.20.0.2
    environment:
      TZ: 'Europe/Paris'
      # Uncomment the next line if you uncomment anything in the section
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /container-data/Nginx-proxy/data:/data
      - /container-data/Nginx-proxy/letsencrypt:/etc/letsencrypt
networks:
    nginx:
      external: true
      name: nginx