services:
  resilio-sync:
    image: linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /container-data/resilio:/config
      - /container-data/resilio:/downloads
      - nas:/sync
    networks:
      nginx:
        ipv4_address: 172.20.0.6
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
networks:
    nginx:
      external: true
      name: nginx
volumes:
  nas:
    external: true